applications:

  meetup:
    project: default
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    source:
      repoURL: git@github.com:cloud-native-aixmarseille/2025-12-10-argocdcmp.git
      targetRevision: main
      path: src/manifests
      # NOTE: this can also be declared as a default plugin but lets be specific
      # plugin:
      #   name: meetup-cmp
      #   env:
      #     - name: FACTID
      #       value: "f0bed94a1b1a4bfc09f231f96a8b25bf"
